### ISSUE TITLE
MainActivity: Error: Speech recognition engine error: Other network related errors..

### ISSUE THREAD

**Issue by UnnikrishnanBhargavakurup** [PLNech/musicologist#1]
I am getting the following error. `MainActivity: Error: Speech recognition engine error: Other network related errors..`

How I can fix this?

**Comment by PLNech** [comment]
Hi @UnnikrishnanBhargavakurup, thanks for reporting this!

`Other network related errors` is an error message defined by the [`SpeechRecognizer`](https://developer.android.com/reference/android/speech/SpeechRecognizer), sent by the underlying `SpeechRecognitionService` on your device.

Before exploring solutions, can you tell me more about the context in which you get this issue? 
- Do you get the error every time or only once in a while? 
- Did you successfully use SpeechToText in other apps on this device?
- Does this happen on a specific device or did you reproduce the issue on different devices? 

This error suggests an issue with your device's Speech To Text rather than with the Musicologist itself (which just reports any error coming from the `SpeechRecognizer`). Searching on internet, I can find several potential causes:

- According to [this post](https://1sheeld.com/topic/speechrecognizer-error_network-solved/#post-47131), it could be that the microphone is already in use by another app.
- [This SO answer](https://stackoverflow.com/a/24593835/3109189) suggests that some Samsung devices will face this issue unless one installs the [Google App providing SpeechToText](https://play.google.com/store/apps/details?id=com.google.android.googlequicksearchbox&hl=en).

Finally, I just pushed [a commit](https://github.com/PLNech/musicologist/commit/da47b447a9d13fee0fb0c9ce14cd59227fd99e89) that specifies the EN locale to use (`en-us`). This being specified, you can now use offline SpeechToText by downloading that package:
 - In the Google app, go to Settings > Voice > Offline and download `English-US`
 - Open the musicologist
 - Turn on Airplane mode
 - Press the mic button and start talking.

Of course the musicologist won't reach its backend, but this flow should let you confirm the TTS works on your device. Let me know how it goes!

**Comment by UnnikrishnanBhargavakurup** [comment]
Hi @PLNech,
 
Sorry for reporting this issue, it was a mistake. It's working fine in device. This error was only happening in emulator not in actual device.

Thanks for the help.

**Comment by PLNech** [comment]
Noprob @UnnikrishnanBhargavakurup, glad to see it's resolved! Let me know if I can help with anything else :)

I'm curious, what brought you to this project? Do you have something specific in mind to do with it, or just checking out of curiosity? :)

**Comment by UnnikrishnanBhargavakurup** [comment]
Hi @PLNech ,

> what brought you to this project?

I'm working for a ecommerce company, We are also using Algolia.

> Do you have something specific in mind to do with it

Thought of implementing this in our mobile apps. so started working on a POC if I get approval from my manager we will implement it.

This is a great project thank you very much for sharing the code!
